### ISSUE TITLE
[Question]  Coinage's actual meaning

### ISSUE THREAD

**Issue by kappa-maintainer** [Da-Technomancer/Crossroads#103]
I'm translating Crossroads to Chinese, but I can't find many words' actual meaning. Here is a list of words I want to know it's meaning, origin or root. If such meaning not exist, I will transliterate these words.
Word list:
Densus
Copshowium
Ratiator
Eldrine
Stasisol
Fusas

**Comment by Da-Technomancer** [comment]
All of those words are not real English words- they are made up. All of them (other than ratiator) are fictional materials.
Densus: Density + -us (used in many real material names)
Copshowium: I have no good explanation for this one. Basically a real sounding fake element name (ends in -ium, like most things on the periodic table).
Ratiator: Not a material. A version of the vanilla comparator with "rati-" to imply ratio (because it divides). Probably a modification of whatever is the chinese translation of Comparator makes the most sense.
Eldrine: A combination of eldritch and -ine (used in many element names). Eldritch is used to mean ancient wisdom.
Stasisol: A combination of stasis (meaning unchanging) and -ol (used in many chemical names)
Fusas: A combination of fusion (meaning to combine) and -as (used in many chemical names)

Thank you for taking (what I assume) is a massive undertaking to translate the mod into Chinese, making the mod accessible to many more players :).

**Comment by kappa-maintainer** [comment]
Thanks for your explanation. I believe Bobo's comments will raise more question in the future, so I will keep the issue open until I complete the translation.

**Comment by Da-Technomancer** [comment]
Bobo's comments are meant to be little riddles. In English, this was mostly achieved through intentional misspelling and weird synonyms (for example, instead of blaze rod, "hot rod", which in English could be a blaze rod or a minecart). I don't know much about the Chinese language, but I doubt those two things will translate well. 

If it's possible to somehow make the translation a short or simple riddle, that would be great, but I wouldn't worry too much about it- if you can't find a translation that makes sense, feel free to just make it a simple list of the ingredients.

**Comment by kappa-maintainer** [comment]
What's Phelostogen's root? I think this may be the last coinage I will encounter...

**Comment by Da-Technomancer** [comment]
Phelostogen or phlogiston is a real word, actually. https://en.wikipedia.org/wiki/Phlogiston_theory
Basically it's an old theory about what fire is made of (now disproven).

**Comment by kappa-maintainer** [comment]
Thanks, I know phlogiston, just not sure if they are exactly same word.

**Comment by kappa-maintainer** [comment]
Is 1.16 the only branch accept pull request now? I have finished the translation on 1.12(for personal modpack) but I am not sure if I should continue my work on branches older than 1.16.

**Comment by Da-Technomancer** [comment]
1.16 is the only branch accepting pull requests.
Thank you,

**Comment by kappa-maintainer** [comment]
What is the meaning of Piglin Chestplate and Maxwell's demon's quips?
The current Chinese translation somehow translates the quip into Marx's demon, which is pretty confusing.

**Comment by Da-Technomancer** [comment]
Piglin chestplate: It's a quote from a book. I'm not sure if there is a direct translation- the original joke is that someone confused the word 'incognito' with being in a place called Cognito. 

Maxwell's demon: Maxwell's demon is a thought experiment created by someone named Maxwell (https://en.wikipedia.org/wiki/Maxwell%27s_demon). My first name is Max, and the tooltip is a reference to the similarity of Maxwell and Max.

In both cases, it might be easier to come up with an entirely new quip/joke line that works in Chinese, rather than trying to force a translation.

**Comment by kappa-maintainer** [comment]
Thank you. I have translated the json file and Intro chapter of the patchouli guide book, once I finish all, I will make a pull request.

**Comment by kappa-maintainer** [comment]
I have translated everything in guidebook except Technomancy chapter, and I found some questions I should ask early on: Why did you change beam element to beam alignment? Is it because of its similarity to D&D alignment?

**Comment by Da-Technomancer** [comment]
It is unrelated to D&D. I changed it from element to alignment to make it sound less magical, and to make it less magical thematically.
