### ISSUE TITLE
Make equilibrium cool

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#195]
**Scope**
Reworking the effect of equilibrium, void-equilibrium, and stability. Possibly renaming equilibrium and void-equilibrium.

**Suggestion**
The current equilibrium beam effect (suppressing nearby explosions) should be moved over to stability (current effect: nothing).
Equilibrium and void-equilibrium beams should be given entirely new effects that are actually useful and/or interesting. **I want suggestions for what these effects should do.**

**Justification**
As it stands, equilibrium and void-equilibrium is basically a non-alignment. The effects are basically never used; the preventing-explosions effect of equilibrium is expensive to use and not hugely useful, while the perpetuating explosions effect of void-equilibrium is basically a worse version of the void-stability effect.
Stability doesn't have any effect right now, but giving it the preventing explosions effect of equilibrium would be a way to save the feature in a low-impact (on existing builds) way. 
Any beam alignment with an effect that is never used is basically a wasted feature, and should be reworked. 

**Impact**
It will (hopefully) make equilibrium useful and used, rather than being a 'junk' or 'filler' alignment as it is currently. The (few) existing builds using the equilibrium effect will need to switch to using stability (an easy change) or void-stability as appropriate. 
The full impact will depend on what the new equilibrium _is_.

**Comment by Tobanyi** [comment]
Idea:
Equilibrium: prevents liquid source blocks from flowing outward
Void-Equilibrium: reverses "gravity" for liquids (gases flow down, liquids flow up)

**Comment by StrangerSon71** [comment]
What about a tractor beam? I was thinking about this mods lack of item collection, and this could provide that along with a lot of fun effects. This would certainly come with a name change (Maybe Force?), and Void would be push. Only real problem I can think of is casually walking into beam storage and getting yanked around. Maybe it doesn't work on mobs or players except out of a beam cannon?

**Comment by Spontaneo** [comment]
Equilibrium could  rapidly force a block to environment temp and void Equilibrium could change environment in area based on temp of target block hit with radius based off power

Example could range from water evaporated to desertification to area is now a lake of lava and charcoal or other extreme is water to ice and snow and ground changes to packed ice and blue ice

**Comment by CvoidWyvern** [comment]
Making this a gravity related beam would be nice especially as this is a good chance to implement one without breaking existing setups. Here's a different take on that: have equilibrium be stillness/inertia/resistance and void equilibrium be force, using void equilibrium when a gravity related beam is needed. Equilibrium would cause a block to be immovable, unbreakable, and untransmutatable for a duration, like Thaumcraft warding but temporary. Void equilibrium could be used to push blocks like a piston would, as well as subtracting the status applied by equilibrium. To make the warding more practical for long term setups, the warding duration could be something like 2^(power/5) seconds, 68 real years is effectively infinite in a minecraft world. Higher strengths of force could act like the multipiston, moving multiple blocks depending on power, maybe dependent on how many blocks get moved as well.

**Comment by Roatze** [comment]
Personally i think it could be interesting with something like equalizing the energy(heat/rotary) of blocks in a radius of size beam power. 
Transferring for example heat energy from hot blocks to cold blocks until they reach an average temperature. 
Or transferring joules from a fast gear system to a slow system. 

Like a form of wireless energy transfer between all blocks in the radius towards the average.
With void-equilibrium then transferring energy away from the average with hot/fast systems draining heat/speed from colder systems until there is no more heat/speed to drain having reached either absolute zero or a speed of 0.
For rotary systems it would probably be best to equalize based on radians adjusted for gearing instead of joules contained in gears.

If you want to be really fancy the temperature/radians the energy transfer equalises towards/away form could be the temperature/radians of the block the beam is impacting. 
Like say shooting a equilibrium beam at a block thats 300 degrees and then all blocks in radius hotter than 300 transfers heat to blocks colder than 300. Or a void-equilibrium beam on a block 0 degrees hot wirelessly draining generated heat from sample freezers towards heat reservoirs.

**Comment by Da-Technomancer** [comment]
Thank you to everyone for their suggestions; in the end, a combination of the gravity and force ideas won out, mainly due to their wide versatility.
The exact implementation details are in the commit above.
