### ISSUE TITLE
[Question/Suggestion] Needed Crucible Heat - Metal smelting points 

### ISSUE THREAD

**Issue by accessdenied0** [Da-Technomancer/Crossroads#261]
**Suggestion**
Hey! I really got curious after playing in a pack abotu your mod and after I binged watched your Tutorial Vids on Youtube, I really loved everything about it! 

I just had one request in my mind which I think would be really fitting:
The heat needed for each Metal smelted in the Crucible, since each Metal has a slight different heat needed, I would love to see it reflected in this step...
Like for example that Copper needs +1.085 °C or Iron +1250 °C.

**Current Behavior [Optional]**
Currently, every Metal despite different melting points, all get molten at 1k.

**Justification**
I would love to use this for some Packs, and since Temperature matters in a lot of different Parts as well, I feel this feature might fit right in, in addition of a lil' bit immersive feel. ´^^

**Comment by Da-Technomancer** [comment]
Hi! Glad you're enjoying the mod.

The Crucible used to work that way with different melting points in older versions (it was changed to the way it works now in Crossroads 1.5.0). 
It was changed because the crucible uses heat while it's above the melting point temperature, and having that 'start-using-heat' temperature change based on the contents led to heat systems with crucibles in them being kind of unreliable, because there was this massive heat-consumption that would switch on and off at various different temperatures.
