### ISSUE TITLE
Incubator not producing correct items

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#274]
**Describe the bug**
![image](https://github.com/Crossroads-Development/Crossroads/assets/11035641/c65528d3-be3c-499a-9d46-f7a0ce3b9700)

**Comment by Autoskip** [comment]
This bug is reliably rearing its head in the current Crossroads Discord's Minecraft server - I'm only ever getting one good genetic plasmid per server restart (which is happening twice a day at 1:50 am/pm GMT if you want to come on and check), and usually the failure state is no output whatsoever, and for that reason, I haven't been trying cloning very often (though when I did, I usually didn't get more than one success there either)

I don't know if it's working once across the server and my team has just been getting in first, or multiple incubators are managing to get their own success, but moving the incubator didn't help last I checked (which was some time ago).

**Comment by Mara666** [comment]
Hai, I am Moth from the screenshot, I am playing on the latest 1.20.1 release using forge 47.2.20 on a single player world. it seems upon logging into the world the incubator works as expected but only once per restart, I tested this in creative and tried providing a redstone signal to see if it changed anything, it didn't.
I used the data get command on the incubator while it was running.
When using the data get command on the incubator after loading the world (when it did work) it said:
`12, -60, -11 has the following block data: {target: 48, inv_1: {id: "minecraft:egg", Count: 16b}, z: -11, x: 12, mot_1: 0.0d, progress: 789.0d, init_heat: 1b, inv_0: {id: "crossroads:embryo", tag: {cr_genetics: {entity_name: "minecraft:sheep", degradation: 3, respawning: 0b, loyal: 0b, originating_uuid: [I; -1784218306, 1233537018, -1981387946, 658469726], potions: []}, cr_was_frozen: 0b, cr_spoil_time: 194370L}, Count: 1b}, ForgeCaps: {"improvedmobs:opened_flag": {HasBeenOpened: 1b}}, id: "crossroads:incubator", y: -60, temp: 49.04999999999993d, server: 1b}`
The second time when it didn't work:

`12, -60, -11 has the following block data: {target: 60, inv_1: {id: "minecraft:egg", Count: 14b}, z: -11, x: 12, mot_1: 0.0d, progress: 257.0d, init_heat: 1b, inv_0: {id: "crossroads:embryo", tag: {cr_genetics: {entity_name: "minecraft:sheep", degradation: 3, respawning: 0b, loyal: 0b, originating_uuid: [I; -1784218306, 1233537018, -1981387946, 658469726], potions: []}, cr_was_frozen: 0b, cr_spoil_time: 194370L}, Count: 1b}, ForgeCaps: {"improvedmobs:opened_flag": {HasBeenOpened: 1b}}, id: "crossroads:incubator", y: -60, temp: 69.04999999999991d, server: 1b}`
except for the the temperature difference they seem the same but maybe I'm overlooking something, the improved mobs flag is from another mod I have installed but I don't think it's the problem
I did use the same embryo
I don't  know how helpful any of this is I don't really know how to test this stuff

**Comment by Autoskip** [comment]
Did some more testing of my own (this time with the latest version on 1.20.1 neo forge 47.1.88 (and no unneeded mods - not even jei), and it's behaving the same as on the 1.19.2 server - and after doing some more comprehensive testing, here's what I found:

- Embryos and genetic plasmids seem to get one success each per world load, but it doesn't seem to matter what the embryo is for (tested on sheep, followed by cow - the cow failed)
- It doesn't matter if you use different incubators (though I did only test the next chunk over)
- It's not due to the embryo being spoiled by the time that the egg is made (I had no problem making multiple clones from the same copied embryo in my inventory, assuming I reloaded the world between clones)
- Getting multiple incubators to start (and, by extension, finish) at the same time didn't help - all 4 incubators I did this test with showed having a successful clone, but when I removed one of them, the other ones disappeared, and when I hoppered the finished spawn eggs out, only one made it.

**Comment by Da-Technomancer** [comment]
Fixed in the next update.
Thank you to everyone for your thorough investigation- I would have struggled to find the cause of this bug (or reproduce it) if you hadn't discovered that it only affects the second craft onwards.

For the curious- the bug was caused by a bit of sloppiness in the incubator code. It crafts the item fine, but then (by mistake) modifies the saved recipe afterwards. Or more specifically, makes the output slot of the incubator control what the recipe makes.

**Comment by Da-Technomancer** [comment]
The fix has reportedly not worked
