### ISSUE TITLE
Unidict compatibility problems 

### ISSUE THREAD

**Issue by Mcniiby** [Da-Technomancer/Crossroads#57]
Because crossroads gears are oredictionary, it causes the unidict mod from disabling all crossroads gear recipes and hiding them in NEI/JEI thus making rotary impossible since Crossroads doesn't work with other mods gears.

**Comment by Da-Technomancer** [comment]
I see 3 solutions to this. Either I remove oreDict from the gears (Which I don't want to do, oreDict being an intended feature), the user configures unidict to allow Crossroads gears, or the UniDict dev does something on there end to make it possible to mark a recipe as crucial. As I'm not going to remove oreDict from the gears, that means there's nothing I can really do.

**Comment by SuiguraTaiki** [comment]
Just want to add in a note for whoever still has this issue, but this is not on Crossroads' end:

UniDict uses a priority system in its config file. The higher the mod id is in its internal list, the higher priority it will be. Crossroads is not supported by Unidict, therefore it has no integrated priority. The user can just manually input the Crossroads on top of the priority list, and it should work fine.

This is also relevant when using Instantunify or other similar mods, since it pulls its settings directly from UniDict, literally disabling the use of Crossroad's regular gears. Toggle and Large Gears still work as intended.
