### ISSUE TITLE
Idea-Electrcity

### ISSUE THREAD

**Issue by CTH999** [Da-Technomancer/Crossroads#69]
So, I think I came up with a Crossroads-y electricity idea. So, he it is...
For generating, the generator uses coils. More coils= more Mass, and more electricity. More energy in gears= more electricity. You want to get as many coils, without stopping the gears.
Wires take into account resistance, which, with more voltage is less. Iron Is horrible, while copper's quite good. Gold is slightly better than coper, but so little, that it's negligible unless you are doing a very long range wire.
There could be a faster furnace, lights, and a special "Light Light" for making a magic beam of the light element for a lot of energy. These are just ideas though.

Then, there could be a fusion reactor, maybe. It generates a lot of rotary power, but requires electricity to run.

This a just an idea. if you like it, great. If not, fine too. It's your choice.

**Comment by Da-Technomancer** [comment]
I may use some of these at some point, as the suggested system of managing coil mass sounds very Crossroads-y, and I quite like it. Thank you for your suggestion. 

I'm closing this issue because the github issue system isn't really for suggestions so much as bug reports, and I must ask that in the future you make suggestions in other ways (such as the discord).

**Comment by CTH999** [comment]
I'll remember that.
Thanks
