### ISSUE TITLE
Server lag in com.Da_Technomancer.crossroads.EventHandlerCommon.worldTick()

### ISSUE THREAD

**Issue by LemADEC** [Da-Technomancer/Crossroads#88]
As of crossroads-1.12.2-1.11.0, server lag is observed in LagGoogles and Warmroast profilers:
![image](https://user-images.githubusercontent.com/4776032/44206336-b8d61800-a159-11e8-99c5-b5828748dd1e.png)

![image](https://user-images.githubusercontent.com/4776032/44206237-76144000-a159-11e8-9eb5-aedf5c5fb238.png)

This could be due to GC lag from allocating too many temporary objects.

From a quick code review, I can see BlockPos being created in a loop,
here with new BlockPos()
https://github.com/Da-Technomancer/Crossroads/blob/1.12-Schism/src/main/java/com/Da_Technomancer/crossroads/EventHandlerCommon.java#L255

here with new BlockPos()
https://github.com/Da-Technomancer/Crossroads/blob/1.12-Schism/src/main/java/com/Da_Technomancer/crossroads/EventHandlerCommon.java#L280

and here through BlockPos.up()
https://github.com/Da-Technomancer/Crossroads/blob/1.12-Schism/src/main/java/com/Da_Technomancer/crossroads/EventHandlerCommon.java#L291

In adjustPosToNearbyEntity(), remember that calling getEntitiesWithinAABB() is fairly CPU intensive. You can probably directly get the list of entities in a given chunk and save some CPU time.

In the field scan loop, the HashSet size isn't preallocated, try setting it to 10 or 20 to avoid memory reallocation lag, like so:
https://github.com/Da-Technomancer/Crossroads/blob/1.12-Schism/src/main/java/com/Da_Technomancer/crossroads/EventHandlerCommon.java#L139
```
HashSet<Long> toRemove = new HashSet<Long>(20);
```

**Comment by Da-Technomancer** [comment]
The efforts you have clearly gone to in order to help fix this issue are very much appreciated. The issues you've highlighted will get fixed in the next version.

That being said, I doubt the issues you've with BlockPos creation are the source of the lag, as they are only initialized if `if(chargeLevel > 0.5F)` passes, which it only will if you've gone into later game Alchemy and used the atmospheric charging stuff. 

The whole method really is due a cleanup, and I'll deal with it in the next update.

Thank you again for going to all this trouble to locate the source of this issue.
