### ISSUE TITLE
[Suggestion] Inert glass or config option

### ISSUE THREAD

**Issue by DaedalusGame** [Da-Technomancer/Crossroads#94]
I realize that this mod isn't really about making things aesthetically pleasing (infact, it actually appeals a lot to my aesthetic, which generally prefers moving/functional parts over pretty blocks), but a glass block that ignores magical beams would be cool to have for building. Lenses partially fit this description, but they aren't full blocks, and putting lots of them in sequence to inlay a beam in the floor looks sorta odd. 

Failing a specific glass block being created for this purpose, a config option to declare certain blocks inert to beams would be cool and would also solve a seperate issue where beams will collide with a lot of blocks they probably shouldn't collide with, like floating lamps from a variety of mods, or air marker blocks (i remember that kind of thing being all the rage with railcraft, don't know if mods still do that nowadays)

**Comment by Da-Technomancer** [comment]
Two new beam permeable blocks (a glass-like block and an opaque block) have been added for 1.13. 

It should be noted that there is, and has never been, any issue with colliding with Railcraft air-lights (or similar devices) due to the old system for determining if a block was solid to beams used isAir checks (and Railcraft air-lights are considered air).

**Comment by Da-Technomancer** [comment]
Closing this to cleanup the feed, as this is implemented in the betas.
