### ISSUE TITLE
Mechanical Arm crash

### ISSUE THREAD

**Issue by googobbug** [Da-Technomancer/Crossroads#96]
The crash happens when you place a mechanical arm on top of another mechanical arm that's attempting to break blocks.

To replicate:
Place down a mechanical arm
Give it a redstone signal of 7
Place a second mechanical arm on the first one's claw

Log: https://paste.dimdev.org/dorucaxigi.mccrash

Worth noting is that trying to reopen the world gives a different crash log.
Log: https://paste.dimdev.org/okabamigef.mccrash

**Comment by Da-Technomancer** [comment]
A few basic questions to help me fix this quickly:

-Which dimension did this happen in? Did this happen in a workspace dimension?
-The two linked crash logs are the same. Did you accidentally upload the wrong crash log for one of the links? (The errors are the same line for line, only the timestamps are different). 
-Is the world recoverable, or is this a world-breaking crash I need to fix ASAP?


In the meantime, here's a suggested fix: 
Go into the Crossroads config, and enable the config option for wiping invalid dimension mappings. 
Before re-starting the server, back up the world file. 
Re-launch the server.
The server will crash. This is intentional while it re-generates some saved data.
Re-launch the server again. It should work now.
You may want to re-disable the wipe-invalid-dimensions config.

The downside of using this method is it will delete one or more workspace dimensions that were causing the error. This is why you backed up the world file before hand, as depending on the nature of the bug, it may be recoverable from the backup. 

Thank you for your report.

**Comment by googobbug** [comment]
- I did this in the overworld.
- Yeah, I linked the wrong log on accident. Here's the correct first log: https://paste.dimdev.org/dorucaxigi.mccrash
- I was able to open the world by closing and relaunching minecraft.
